In [1]:
# To perform simple linear regression using gradient descent

import numpy as np
import pandas as pd

df = pd.read_csv('Salary_Data.csv') # Input your own data here

d = df.values

x = d[:,0].reshape(-1,1)
y = d[:,1].reshape(-1,1)

import matplotlib.pyplot as plt
%matplotlib inline

features = np.random.randn(np.size(x[:,0]),2)

features[:, 0] = 1
features[:, 1] = x[:, 0]

# To calculate the cost function

def cost_func(h, features, y):
    cost = 0
    for i in range(0, np.size(features[:, 1])):
        cost = cost + (pred(h, features[i]) - y[i][0])**2
    
    return ((1/2)*cost)

#To calculate the predicted value

def pred(h, n):
    f = 0
    for i in range(0, np.size(h)):
        f = f + h[i]*n[i]
    return f

dt = np.dtype(np.int64)

# To perform gradient descent

def grad_desc(h, features, y, rate):
    h = np.array(h, dtype = dt)
    for i in range(0, np.size(features[:, 1])):
        for j in range(0, np.size(h)):
            h[j] = h[j] + rate*(y[i][0] - pred(h, features[i]))*features[i][j]
    
    return h

# To calculate the difference in the magnitude of the old and new coefficients

def mag(h_old, h_new):
    mag_old = 0
    mag_new = 0
    for i in range(0, np.size(h_old)):
        mag_old = mag_old + (h_old[i])**2
        mag_new = mag_new + (h_new[i])**2
    
    return mag_old, mag_new

h_old = np.array([0,0], dtype = dt)
h_new = np.array(grad_desc(h_old, features, y, 0.01), dtype = dt)

mag_old, mag_new = mag(h_old, h_new)

# To continue the process of gradient descent until convergence

while(abs(mag_old - mag_new) >0.001):
    h_old = h_new
    h_new = grad_desc(h_new, features, y, 0.01)
    mag_old, mag_new = mag(h_old, h_new)

h_new

pred(h_new, features[1]), y[1][0]

(39362.0, 46205.0)

In [2]:
df.head(10)

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0
7              3.2  54445.0
8              3.2  64445.0
9              3.7  57189.0